config/routes.rb
Rails.application.routes.draw do
  resources :clients


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root :to => "users#home"
	devise_for :users
	resources :users do
		get 'home', :on => :member
		get 'admin_home', :on => :member
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  def require_admin
    unless current_user.is_admin
      flash[:error] = "You must be an admin in to access that section" 
      redirect_to home_user_path(:id => current_user.id) # Prevents the current action from running
    end
  end
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  
  # GET /clients
  # GET /clients.json
  def index
    @Clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @client.users << current_user

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:uid, :moniker, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!

#GET users/home
def home
	if current_user.is_admin? then
		redirect_to admin_home_user_path(:id => current_user.id)
	end
	
	
end

#GET users/admin_home
def admin_home
	@Clients = Client.all
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<% content_for :nav do %>
	<%  render partial: "layouts/navigation", locals: {active: "clients"} %>
<% end %>
<% content_for :main do %>
	<%= form_for(client) do |f| %>
	  <% if client.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

		  <ul>
		  <% client.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>

	  <div class="field">
		<%= f.label :uid %>
		<%= f.text_field :uid %>
	  </div>

	  <div class="field">
		<%= f.label :moniker %>
		<%= f.text_field :moniker %>
	  </div>

	  <div class="actions">
		<%= f.submit %>
	  </div>
	<% end %>
<% end %>

app/views/clients/_index.html.erb
<h1>Clients</h1>

	<table>
	  <thead>
		<tr>
		  <th>Uid</th>
		  <th>Moniker</th>
		  <th>User</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
		<% @Clients.each do |client| %>
		  <tr>
			<td><%= client.uid %></td>
			<td><%= client.moniker %></td>
			<td><%= client.admin.email %></td>
			<td><%= link_to 'Show', client %></td>
			<td><%= link_to 'Edit', edit_client_path(client) %></td>
			<td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>

	<br>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>


<% content_for :sidebarwide do %>
	<table class="table">
		<tr>
		<td class="danger"><%= link_to 'Show', @client %></td>
		<tr>
		<td class="danger"><%= link_to 'Back', clients_path %></td>
	</table>
<% end %>

app/views/clients/index.html.erb
<% content_for :nav do %>
	<%  render partial: "layouts/navigation", locals: {active: "clients"} %>
<% end %>

<% content_for :main do %>
	<% if @Clients.empty? then %>
		<h3>PLACE HOLDER INFO</h3>
	<% else %>
		<%= render "index" %>
	<% end %>
<% end %>
<% content_for :sidebarwide do %>
	<table class="table">
		<tr>
		<td class="danger"><%= link_to 'New Client', new_client_path %></td>
	</table>
<% end %>

app/views/clients/new.html.erb
	<h1>New Client</h1>

	<%= render 'form', client: @client %>

<% content_for :sidebarwide do %>
	<table class="table">
		<tr>
		<td class="danger"><%= link_to 'Back', clients_path %></td>
	</table>
<% end %>

app/views/clients/show.html.erb
<% content_for :nav do %>
	<%  render partial: "layouts/navigation", locals: {active: "clients"} %>
<% end %>

<% content_for :main do %>
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Uid:</strong>
	  <%= @client.uid %>
	</p>

	<p>
	  <strong>Moniker:</strong>
	  <%= @client.moniker %>
	</p>

	<p>
	  <strong>Admin:</strong>
	  <%= @client.users.first.email%>
	</p>
<% end %>
<% content_for :sidebarwide do %>
	<table class="table">
		<tr>
		<td class="danger"><%= link_to 'Edit', edit_client_path(@client) %></td>
		<tr>
		<td class="danger"><%= link_to 'Back', clients_path %></td>
		<tr>
		<td class="danger"><%= link_to 'New Client', new_client_path %></td>
	</table>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
<div class="navbar-header">
  <a class="navbar-brand" href="#">PitCrew</a>
</div>
<ul class="nav navbar-nav">
  <% if user_signed_in? %>
    
    	<% if active == "clients" %>
    		<li class="active" >
    	<% else %>
    		<li>
    	<% end %>
    	<%= link_to('Clients', clients_path) %>
      </li> 
  <% end %>
</ul>
<ul class="nav navbar-nav navbar-right">
	<% if !user_signed_in? %>
		<% if active != "login" %>
			<li>
			<%= link_to('Login', new_user_session_path)  %>  
			</li>
		<% end %>
		<% if active == "admin" %>
				<li class="active" >
		<% else %>
				<li>
		<% end %>
		<%= link_to('SignUp', new_user_registration_path) %>
		</li>
    <% else %>
    	<% if active == "account" %>
    		<li class="active" >
    	<% else %>
    		<li>
    	<% end %>
      	<%= link_to('Edit account', edit_user_registration_path) %>
    	</li>
    	
		<li>
    	<%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    	</li>
	<% end %>
</ul>
</div>
</nav>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pit Crew" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head) %>
  </head>

  <body>
 	<%= yield :nav %>		
	<div id="outter-container-area" class="container-fluid">
		<div class="row">
			<div id="alert-area" class="col-md-12">
				<% if notice %>
					<p class="alert alert-success"><%= notice %></p>
				<% end %>
				<% if alert %>
					<p class="alert alert-danger"><%= alert %></p>
				<% end %>
				<%= yield %>
			</div>
		</div>
		<div class="row">
			<div id="main-content-area" class="col-md-12">
				<% if content_for?(:sidebar) %>
					<div id="sidebar" class="col-md-1"> 
						<h3>Actions</h3>
						<%= yield :sidebar %>
					</div>
				<% else %>
					<% if content_for?(:sidebarwide) %>
						<div id="sidebarwide" class="col-md-2"> 
							<h3>Actions</h3>
							<%= yield :sidebarwide %>
						</div>
					<% end %>
				<% end %>
            	<% if content_for?(:sidebarwide) %>
            		<div id="content" class="col-md-10 container-fluid">
            	<% else %>
            		<div id="content" class="col-md-11 container-fluid">
            	<% end %>
            	<%= yield(:main) %>
			</div>
		</div>
	</div>
  </body>
</html>

app/views/users/admin_home.html.erb
<% content_for :nav do %>
	<%  render partial: "layouts/navigation", locals: {active: ""} %>
<% end %>


<% content_for :main do %>
	<div class="col-md-6">
		<h1>My Clients</h1>
		<% if @Clients.empty? then %>
			<h3>PLACE HOLDER INFO</h3>
		<% else %>
			<%= render "clients/index" %>
		<% end %>
	</div>

	<div class="col-md-6">
		<h1>Crew Members<h1>
		<h3>PLACE HOLDER INFO<h3>
	</div>
<% end %>
<% content_for :sidebarwide do %>
	<table class="table">
		<tr>
		<td class="danger"><%= link_to 'Back', clients_path %></td>
	</table>
<% end %>

app/views/users/home.html.erb
<% content_for :nav do %>
	<%  render partial: "layouts/navigation", locals: {active: ""} %>
<% end %>

<% content_for :main do %>
	<div class="col-md-6">
		<h1>Tasks</h1>

		<h3>PLACE HOLDER INFO<h3>
	</div>

	<div class="col-md-6">
		<h1>Ad-Hoc Tasks<h1>
		<h3>PLACE HOLDER INFO<h3>
	</div>
<% end %>
<% content_for :sidebarwide do %>
	<table class="table">
		<tr>
		<td class="danger"><%= link_to 'Back', clients_path %></td>
	</table>
<% end %>